/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户信息
         * @description 根据用户ID获取用户详细信息
         */
        get: operations["getUser"];
        /**
         * 更新用户
         * @description 更新用户信息（仅本人或管理员）
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * 删除用户
         * @description 删除指定用户
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 修改密码
         * @description 用户修改自己的密码（仅本人）
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取所有用户
         * @description 获取系统中所有用户列表
         */
        get: operations["getAllUsers"];
        put?: never;
        /**
         * 创建用户
         * @description 创建新用户账号
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码
         * @description 通过邮箱重置密码
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/check-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 邮箱唯一性校验
         * @description 检查邮箱是否已被注册
         */
        post: operations["checkEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/internal/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 内部接口-按ID查询用户认证信息
         * @description 供认证服务Feign调用，按用户ID查询返回含密码哈希的用户数据
         */
        get: operations["getUserFeignById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/internal/auth/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 内部接口-查询用户认证信息
         * @description 供认证服务Feign调用，返回含密码哈希的用户数据
         */
        get: operations["getUserForAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
        };
        /** @description 更新用户请求 */
        UpdateUserRequest: {
            /**
             * @description 用户名
             * @example john_doe
             */
            username?: string;
            /**
             * @description 邮箱地址
             * @example john@example.com
             */
            email?: string;
            /**
             * @description 昵称
             * @example John
             */
            nickname?: string;
            /**
             * @description 头像URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
        };
        RUserDTO: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserDTO"];
        };
        /** @description 用户信息 */
        UserDTO: {
            /**
             * @description 用户ID
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id?: string;
            /**
             * @description 用户名
             * @example john_doe
             */
            username?: string;
            /**
             * @description 邮箱地址
             * @example john@example.com
             */
            email?: string;
            /**
             * @description 昵称
             * @example John
             */
            nickname?: string;
            /**
             * @description 头像URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
            /**
             * @description 角色: USER / ADMIN
             * @example USER
             */
            role?: string;
            /**
             * Format: int32
             * @description 状态: 0-禁用 1-正常
             * @example 1
             */
            status?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updatedAt?: string;
        };
        /** @description 修改密码请求 */
        ChangePasswordRequest: {
            /**
             * @description 原密码
             * @example oldPassword123
             */
            oldPassword: string;
            /**
             * @description 新密码
             * @example newPassword456
             */
            newPassword: string;
        };
        /** @description 创建用户请求 */
        CreateUserRequest: {
            /**
             * @description 用户名
             * @example john_doe
             */
            username: string;
            /**
             * @description 邮箱地址
             * @example john@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example password123
             */
            password: string;
            /**
             * @description 昵称
             * @example John
             */
            nickname?: string;
            /**
             * @description 头像URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
        };
        /** @description 重置密码请求 */
        ResetPasswordRequest: {
            /**
             * @description 注册邮箱
             * @example john@example.com
             */
            email: string;
            /**
             * @description 新密码
             * @example newPassword789
             */
            newPassword: string;
        };
        /** @description 邮箱唯一性校验请求 */
        EmailCheckRequest: {
            /**
             * @description 待校验邮箱
             * @example john@example.com
             */
            email: string;
        };
        RBoolean: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: boolean;
        };
        RListUserDTO: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserDTO"][];
        };
        RUserFeignDTO: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserFeignDTO"];
        };
        /** @description 供认证服务Feign调用的用户信息 */
        UserFeignDTO: {
            /** @description 用户ID */
            id?: string;
            /** @description 用户名 */
            username?: string;
            /** @description 邮箱 */
            email?: string;
            /** @description 密码哈希 */
            passwordHash?: string;
            /** @description 角色: USER / ADMIN */
            role?: string;
            /**
             * Format: int32
             * @description 状态: 0-禁用 1-正常
             */
            status?: number;
            /** @description 昵称 */
            nickname?: string;
            /** @description 头像URL */
            avatarUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 原密码错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    getAllUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RListUserDTO"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserDTO"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 邮箱未注册 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    checkEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RBoolean"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    getUserFeignById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserFeignDTO"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    getUserForAuth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserFeignDTO"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
}
