/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 注册新用户账号，注册成功自动登录返回token
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 使用refreshToken换取新的accessToken
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登出
         * @description 登出当前用户（客户端清除token即可）
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 使用用户名或邮箱 + 密码登录，返回accessToken和refreshToken
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前用户信息
         * @description 根据网关传递的X-User-Id获取当前登录用户信息
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RVoid: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
        };
        /** @description 注册请求 */
        RegisterRequest: {
            /**
             * @description 用户名
             * @example john_doe
             */
            username: string;
            /**
             * @description 邮箱地址
             * @example john@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example password123
             */
            password: string;
            /**
             * @description 昵称
             * @example John
             */
            nickname?: string;
            /**
             * @description 头像URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
        };
        /** @description 认证响应 */
        AuthResponse: {
            /** @description 访问令牌 */
            accessToken?: string;
            /** @description 刷新令牌 */
            refreshToken?: string;
            /**
             * Format: int64
             * @description 访问令牌过期时间(秒)
             */
            expiresIn?: number;
            user?: components["schemas"]["UserDTO"];
        };
        RAuthResponse: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["AuthResponse"];
        };
        /** @description 用户信息 */
        UserDTO: {
            /**
             * @description 用户ID
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id?: string;
            /**
             * @description 用户名
             * @example john_doe
             */
            username?: string;
            /**
             * @description 邮箱地址
             * @example john@example.com
             */
            email?: string;
            /**
             * @description 昵称
             * @example John
             */
            nickname?: string;
            /**
             * @description 头像URL
             * @example https://example.com/avatar.jpg
             */
            avatarUrl?: string;
            /**
             * @description 角色: USER / ADMIN
             * @example USER
             */
            role?: string;
            /**
             * Format: int32
             * @description 状态: 0-禁用 1-正常
             * @example 1
             */
            status?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updatedAt?: string;
        };
        /** @description 刷新令牌请求 */
        RefreshTokenRequest: {
            /** @description 刷新令牌 */
            refreshToken: string;
        };
        /** @description 登录请求 */
        LoginRequest: {
            /**
             * @description 用户名或邮箱
             * @example john@example.com
             */
            identifier: string;
            /**
             * @description 密码
             * @example password123
             */
            password: string;
        };
        RUserDTO: {
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: components["schemas"]["UserDTO"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RAuthResponse"];
                };
            };
            /** @description 参数错误或用户名/邮箱已存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description refreshToken无效或已过期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RAuthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 用户名或密码错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RAuthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 获取成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
            /** @description 未登录 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RUserDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RVoid"];
                };
            };
        };
    };
}
